# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target '20_AFNetworking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20_AFNetworking

  target '20_AFNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20_AFNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking', '~> 3.2.1'

end
