# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'

target '16_CoCoPodUse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 16_CoCoPodUse

  target '16_CoCoPodUseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '16_CoCoPodUseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.1'

end
