# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target '18_DataPersistenceFMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 18_DataPersistenceFMDB

  target '18_DataPersistenceFMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '18_DataPersistenceFMDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'FMDB', '~> 2.7.5'

end
